version: 2
registries:
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    registries:
      - public
    directory: /
    schedule:
      interval: weekly
    groups:
      xunit:
        patterns:
          - "xunit*"
