name: "Build & Test"
permissions:
  checks: write

on:
  workflow_dispatch:
  pull_request:
    branches:
      - *
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        shell: bash
        run: dotnet restore

      - name: Check formatting
        shell: bash
        run: dotnet format --verify-no-changes --report ./

      - name: Build
        shell: bash
        run: dotnet build --no-restore -c Release

      - name: Unit tests
        shell: bash
        run: dotnet test tests/introl.timesheets.api.tests.unit --no-build --no-restore -c Release --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Acceptance tests
        shell: bash
        run: dotnet test tests/introl.timesheets.api.tests.acceptance --no-build --no-restore -c Release --verbosity normal --logger "trx;LogFileName=test-results.trx"
        if: success() || failure()

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .net test reporter
          path: "**/test-results.trx"
          reporter: dotnet-trx